[project]
authors = ["Jack Myers <jack.myers@intel.com>"]
channels = ["https://software.repos.intel.com/python/conda/", "conda-forge"]
description = "Add a short description here"
name = "template-cpp-project"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

# Common among all toolchains
[dependencies]
cmake = ">=3.30.5,<4"
ninja = ">=1.12.1,<2"
ccache = ">=4.10.1,<5"
pkg-config = ">=0.29.2,<0.30"
git = ">=2.47.0,<3"
cmake-format = ">=0.6.13,<0.7"
clang-format = ">=18.1.8,<20"
clang-tools = ">=18.1.8,<20"
cppcheck = ">=2.15.0,<3"
python = ">=3.12.5,<4"

[target.linux-64.dependencies]
wget = ">=1.21.4,<2"

[target.linux-64.activation]
scripts = ["activation/linux.sh"]

[target.win-64.activation]
scripts = ["activation/msvc.bat"]


# CLANG Toolchain
[feature.clang.dependencies]
clangdev = ">=18.1.8,<20"

[feature.clang.target.linux-64.dependencies]
clangxx_linux-64 = ">=18,<19"
clang_linux-64 = ">=18,<19"

[feature.clang.target.win-64.dependencies]
vs_win-64 = ">=2022.11,<2023"

[feature.clang.target.win-64.activation]
scripts = ["activation/clang.bat"]

[feature.clang.target.linux-64.activation]
scripts = ["activation/clang.sh"]


# DPCPP Toolchain 
[feature.dpcpp]
platforms = ["linux-64"]

[feature.dpcpp.dependencies]
clangdev = ">=18,<19"

[feature.dpcpp.target.linux-64.dependencies]
clangxx_linux-64 = ">=18,<19"
clang_linux-64 = ">=18,<19"
intel-opencl-rt = ">=2024.2.1,<2025"
intel-fortran-rt = ">=2024.2.1,<2025"
intel-opencl-fpga-emu-rt = ">=2024.2.1,<2025"
ocl-icd = ">=2.3.2,<3"
ocl-icd-system = ">=1.0.0,<2"
clinfo = ">=3.0.21.2.21,<4"
cuda = ">=12.6.2,<13"

[feature.dpcpp.target.linux-64.activation]
scripts = ["activation/dpcpp.sh"]


# MSVC for Windows
[feature.msvc]
platforms = ["win-64"]

[feature.msvc.target.win-64.dependencies]
vs_win-64 = ">=2022.11,<2023"


# GNU GCC Toolchain
[feature.gcc.dependencies]
gcc = ">=14.2.0,<15"
gxx = ">=14.2.0,<15"

[feature.gcc.target.win-64.dependencies]
gcc_win-64 = ">=14.2.0,<15"
gxx_win-64 = ">=14.2.0,<15"

[feature.gcc.target.linux-64.dependencies]
gcc_linux-64 = ">=14.2.0,<15"
gxx_linux-64 = ">=14.2.0,<15"

[feature.gcc.target.linux-64.activation]
scripts = ["activation/gcc.sh"]


# Initialize a CMAKE Project
[feature.cmake-init.pypi-dependencies]
cmake-init = ">=0.40.9, <0.41"

[feature.cmake-init.tasks]
cmake-init = "bash scripts/cmake-init.sh"


# ENVIRONMENTS
[environments]
clang = ["clang"]
gcc = ["gcc"]
msvc = ["msvc"]
dpcpp = ["dpcpp"]
cmake-init = ["cmake-init"]
