CALL "%VCINSTALLDIR%/Auxiliary/vcvarsall.bat"
SET CMAKE_PLAT=
SET CMAKE_GENERATOR_PLATFORM=
SET CMAKE_GENERATOR_TOOLSET=
SET CMAKE_GENERATOR=
SET CMAKE_GEN=
SET CMAKE_TOOLCHAIN_FILE="%PIXI_PROJECT_ROOT%/toolchains/windows.cmake"

